services:
  redis:
    image: redis:7
    container_name: corkcharge-redis
    restart: always
    ports:
      - "6379:6379"
    command: [
      "redis-server",
      "--appendonly", "yes",
      "--requirepass", "${REDIS_PASSWORD}"
    ]
    volumes:
      - redis-data:/data
    env_file:
      - .env

  corkCharge:
    image: jaypark0205/corkcharge:latest
    env_file:
      - .env
    ports:
      - "8000:9000"
    environment:
      - PROD_DB_URL=${PROD_DB_URL}
      - PROD_DB_USER=${PROD_DB_USER}
      - PROD_DB_PASSWORD=${PROD_DB_PASSWORD}
      - OPEN_API_KEY=${OPEN_API_KEY}
      - OPEN_API_BASE_URL=${OPEN_API_BASE_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_S3_BASE_URL=${AWS_S3_BASE_URL}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - NAVER_OAUTH_CLIENT_ID=${NAVER_OAUTH_CLIENT_ID}
      - NAVER_OAUTH_CLIENT_SECRET=${NAVER_OAUTH_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - TZ=Asia/Seoul

volumes:
  redis-data: