services:
  corkCharge:
    image: jaypark0205/corkcharge:latest
    env_file:
      - .env
    ports:
      - "8000:9000"
    environment:
      - PROD_DB_URL=${PROD_DB_URL}
      - PROD_DB_USER=${PROD_DB_USER}
      - PROD_DB_PASSWORD=${PROD_DB_PASSWORD}
      - OPEN_API_KEY=${OPEN_API_KEY}
      - OPEN_API_BASE_URL=${OPEN_API_BASE_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_S3_BASE_URL=${AWS_S3_BASE_URL}
      - TZ=Asia/Seoul
